/* ========= STYLES ========= */
const styles = {
  navbar: {
    background: 'linear-gradient(to right, #2563eb, #9333ea)',
    color: 'white',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    position: 'fixed',
    width: '100%',
    top: 0,
    zIndex: 1000,
  },
  navContainer: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '0 1rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '64px',
  },
  navBrand: { fontSize: '1.5rem', fontWeight: 'bold' },
  navMenu: { display: 'flex', gap: '2rem' },
  navButton: {
    background: 'none',
    border: 'none',
    color: 'white',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '0.5rem 0',
    transition: 'color 0.3s',
  },
  navButtonActive: { borderBottom: '2px solid white' },
  mobileMenuButton: {
    background: 'none',
    border: 'none',
    color: 'white',
    cursor: 'pointer',
    display: 'none',
  },
  pageContainer: {
    minHeight: '100vh',
    background: 'linear-gradient(to bottom right, #eff6ff, #faf5ff)',
    paddingTop: '80px',
  },
  contentWrapper: { maxWidth: '1280px', margin: '0 auto', padding: '3rem 1rem' },
  card: {
    background: 'white',
    borderRadius: '8px',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    padding: '2rem',
    marginBottom: '2rem',
  },
  heading1: {
    fontSize: '3rem',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  heading2: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '1.5rem',
    borderBottom: '2px solid #2563eb',
    paddingBottom: '0.5rem',
  },
  heading3: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '0.5rem',
  },
  paragraph: { color: '#4b5563', lineHeight: '1.8', marginBottom: '1rem' },
  avatar: {
    width: '128px',
    height: '128px',
    background: 'linear-gradient(to right, #2563eb, #9333ea)',
    borderRadius: '50%',
    margin: '0 auto 1.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '2.5rem',
    fontWeight: 'bold',
  },
  button: {
    background: 'linear-gradient(to right, #2563eb, #9333ea)',
    color: 'white',
    padding: '0.75rem 1.5rem',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  badge: {
    display: 'inline-block',
    padding: '0.5rem 1rem',
    borderRadius: '9999px',
    fontSize: '0.875rem',
    margin: '0.25rem',
    fontWeight: '500',
  },
  input: {
    width: '100%',
    padding: '0.75rem',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    marginBottom: '1rem',
  },
  label: { display: 'block', color: '#374151', fontWeight: '600', marginBottom: '0.5rem' },
};

export default styles;